### ISSUE TITLE
Deploying to Tomcat

### ISSUE THREAD

**Issue by SatyaKuppam** [oncoblocks/oncoblocks-rest-demo#1]
I am trying to run this demo, however I am stuck.
After I build the project using
_mvn -U clean install_
 there is no .war file created to deploy to Tomcat.
Moreover _sh target/bin/webapp_ does 
not give me any results. It stops at

> Mar 11, 2015 1:37:34 AM org.apache.catalina.core.ApplicationContext log
> INFO: Initializing log4j from [classpath:log4j.properties]

**Comment by ecerami** [comment]
You can create a war like so:

mvn war:war

or, use the built-in server w/o having to install tomcat:

mvn tomcat:run

**Comment by woemler** [comment]
It appears the documentation in the README is out of date. Ethan, could you update this?

**Comment by woemler** [comment]
I updated the application to remove the Heroku configuration and dependencies, the project should now build the WAR file in maven with `mvn clean install`.  You will have to manually deploy to a web app container, but it should work.

**Comment by ecerami** [comment]
Thanks, Will.
